export const NT_BOOKS = [
  { name: "마태복음",       chapters: 28 },
  { name: "마가복음",       chapters: 16 },
  { name: "누가복음",       chapters: 24 },
  { name: "요한복음",       chapters: 21 },
  { name: "사도행전",       chapters: 28 },
  { name: "로마서",         chapters: 16 },
  { name: "고린도전서",     chapters: 16 },
  { name: "고린도후서",     chapters: 13 },
  { name: "갈라디아서",     chapters: 6  },
  { name: "에베소서",       chapters: 6  },
  { name: "빌립보서",       chapters: 4  },
  { name: "골로새서",       chapters: 4  },
  { name: "데살로니가전서", chapters: 5  },
  { name: "데살로니가후서", chapters: 3  },
  { name: "디모데전서",     chapters: 6  },
  { name: "디모데후서",     chapters: 4  },
  { name: "디도서",         chapters: 3  },
  { name: "빌레몬서",       chapters: 1  },
  { name: "히브리서",       chapters: 13 },
  { name: "야고보서",       chapters: 5  },
  { name: "베드로전서",     chapters: 5  },
  { name: "베드로후서",     chapters: 3  },
  { name: "요한일서",       chapters: 5  },
  { name: "요한이서",       chapters: 1  },
  { name: "요한삼서",       chapters: 1  },
  { name: "유다서",         chapters: 1  },
  { name: "요한계시록",     chapters: 22 },
] as const;

export const TOTAL_NT_CHAPTERS = NT_BOOKS.reduce((sum, b) => sum + b.chapters, 0); // 260
